apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.svc.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: elibrary
  ports:
    - protocol: TCP
      nodePort: {{ .Values.app.svc.nodePort }}
      port: {{ .Values.app.svc.port }}
      targetPort: {{ .Values.app.deploy.containerPort }}
  type: NodePort
