apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: elibrary-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: elibrary.com
      http:
        paths:
          - backend:
              serviceName: {{ .Values.app.svc.name }}
              servicePort: {{ .Values.app.svc.port }}
