namespace: elibrary
app:
  deploy:
    image: butter3126/elibrary
    replicas: 1
    containerPort: 8000
    env:
      allowHost: '"*"'
      dbEngine: '"django.db.backends.mysql"'
      dbUser: root
    fluentdImage: butter3126/app-fluentd
  svc:
    name: app-service
    port: 8000
    nodePort: 30080
  conf:
    logPath: "/var/log/app.log"
    esHost: http://192.168.99.100:9200
    esIndexName: elibrary_api
    esTag: elibrary_api
db:
  deploy:
    replicas: 1
  svc:
    name: mysql-service
    port: 3306
  pvc:
    name: db-claim
    storage: 1Gi
